const MODERATION_THRESHOLD = 0.8;
const MODERATION_ENDPOINT =
  "https://ai-moderation-376071505252.asia-southeast1.run.app/moderate";
const AI_MODERATION_TIMEOUT_MS = 1000;
const AI_MODERATION_CACHE_TTL_MS = 5 * 60 * 1000;
const AI_MODERATION_CACHE_MAX_ENTRIES = 512;
const LINK_PATTERN = /(?:https?:\/\/|www\.)\S+/i;
const PHONE_PATTERN = /(?:\+?\d[\d .-]{8,}\d)/;
const EMOJI_ONLY_PATTERN = /^[\p{Extended_Pictographic}\u200d\ufe0f]+$/u;
const FAST_PATH_SAFE_PHRASES = new Set([
  "hi",
  "hello",
  "hey",
  "alo",
  "xin chào",
  "chào",
  "chào bạn",
  "rất vui được gặp bạn",
]);

const DANGEROUS_KEYWORDS = {
  sexual: [
    "lồn",
    "lon",
    "buồi",
    "buoi",
    "cặc",
    "cac",
    "cu",
    "dương vật",
    "duong vat",
    "âm đạo",
    "am dao",
    "địt",
    "dit",
    "djt",
    "đụ",
    "du",
    "đéo",
    "deo",
    "làm tình",
    "lam tinh",
    "chịch",
    "chich",
    "xxx",
    "sex",
    "s3x",
    "sục",
    "suc",
    "bú",
    "bu",
    "liếm",
    "liem",
    "nứng",
    "nung",
    "thủ dâm",
    "thu dam",
    "đụ nhau",
    "du nhau",
    "quan hệ",
    "quan he",
    "gạ tình",
    "ga tinh",
    "nude",
    "ảnh nóng",
    "anh nong",
    "clip nóng",
    "clip nong",
    "hiếp dâm",
    "hiep dam",
    "rape",
  ],
  hate_or_threat: [
    "giết",
    "giet",
    "chém",
    "chem",
    "đâm",
    "đâm chết",
    "dam chet",
    "đâm mày",
    "dam may",
    "đốt nhà",
    "dot nha",
    "đập chết",
    "dap chet",
    "xử mày",
    "xu may",
    "cho mày chết",
    "cho may chet",
    "đồ súc sinh",
    "do suc sinh",
    "mày liệu hồn",
    "may lieu hon",
    "ra đường coi chừng",
    "ra duong coi chung",
    "tao giết mày",
    "tao giet may",
    "tao chém mày",
    "tao chem may",
    "đánh chết",
    "danh chet",
    "giết cả nhà",
    "giet ca nha",
    "dọa giết",
    "doa giet",
  ],
  grooming: [
  ],
};

module.exports = {
  MODERATION_THRESHOLD,
  MODERATION_ENDPOINT,
  AI_MODERATION_TIMEOUT_MS,
  AI_MODERATION_CACHE_TTL_MS,
  AI_MODERATION_CACHE_MAX_ENTRIES,
  LINK_PATTERN,
  PHONE_PATTERN,
  EMOJI_ONLY_PATTERN,
  FAST_PATH_SAFE_PHRASES,
  DANGEROUS_KEYWORDS,
};
