const MODERATION_THRESHOLD = 0.8;
const AI_MODERATION_CACHE_TTL_MS = 5 * 60 * 1000;
const AI_MODERATION_CACHE_MAX_ENTRIES = 512;
const LINK_PATTERN = /(?:https?:\/\/|www\.)\S+/i;
const PHONE_PATTERN = /(?:\+?\d[\d .-]{8,}\d)/;
const EMOJI_ONLY_PATTERN = /^[\p{Extended_Pictographic}\u200d\ufe0f]+$/u;
const FAST_PATH_SAFE_PHRASES = new Set([
  "hi",
  "hello",
  "hey",
  "alo",
  "xin chao",
  "xin chào",
  "chao",
  "chào",
  "chao ban",
  "chào bạn",
  "rat vui duoc gap ban",
  "rất vui được gặp bạn",
]);

const DANGEROUS_KEYWORDS = {
  sexual: [
    "lồn",
    "lon",
    "buồi",
    "buoi",
    "cặc",
    "cac",
    "cu",
    "dương vật",
    "duong vat",
    "âm đạo",
    "am dao",
    "địt",
    "dit",
    "djt",
    "đụ",
    "du",
    "đéo",
    "deo",
    "làm tình",
    "lam tinh",
    "chịch",
    "chich",
    "xxx",
    "sex",
    "s3x",
    "sục",
    "suc",
    "bú",
    "bu",
    "liếm",
    "liem",
    "nứng",
    "nung",
    "thủ dâm",
    "thu dam",
    "đụ nhau",
    "du nhau",
    "quan he",
    "gạ tình",
    "ga tinh",
    "tìm fwb",
    "tim fwb",
    "tìm ons",
    "tim ons",
    "mại dâm",
    "mai dam",
    "bán dâm",
    "ban dam",
    "nude",
    "clip nóng",
    "clip nong",
    "hiếp dâm",
    "hiep dam",
    "rape",
  ],
  profanity: [
    "địt mẹ",
    "dit me",
    "đụ mẹ",
    "du me",
    "đm",
    "dm",
    "dmm",
    "đmm",
    "đcm",
    "dcm",
    "vãi lồn",
    "vai lon",
    "vãi cả lồn",
    "vai ca lon",
    "vcl",
    "v c l",
    "cút",
    "cút mẹ",
    "cut me",
    "óc chó",
    "oc cho",
    "ngu",
    "ngu như chó",
    "ngu nhu cho",
    "đần",
    "đần độn",
    "dan don",
    "súc vật",
    "suc vat",
    "đồ súc sinh",
    "do suc sinh",
    "rác rưởi",
    "hãm",
    "ham",
    "mất dạy",
    "mat day",
    "vô học",
    "vo hoc",
    "bố láo",
    "bo lao",
    "khốn nạn",
    "khon nan",
    "đồ chó",
    "do cho",
  ],
  harassment: [
    "mày biến đi",
    "may bien di",
    "biến đi",
    "bien di",
    "mày câm đi",
    "may cam di",
    "câm mồm",
    "cam mom",
    "im mồm",
    "im mom",
    "thứ rác rưởi",
    "thu rac ruoi",
    "đồ phế vật",
    "do phe vat",
    "phế vật",
    "phe vat",
    "không đáng sống",
    "khong dang song",
    "đi chết đi",
    "di chet di",
    "tự tử đi",
  ],
  regional_discrimination: [
    "bắc kỳ",
    "bac ky",
    "nam kỳ",
    "nam ky",
    "trung kỳ",
    "trung ky",
    "dân bắc kỳ",
    "dan bac ky",
    "dân nam kỳ",
    "dan nam ky",
    "dân trung kỳ",
    "dan trung ky",
    "bọn bắc kỳ",
    "bon bac ky",
    "bọn nam kỳ",
    "bon nam ky",
    "bọn trung kỳ",
    "bon trung ky",
    "lũ bắc kỳ",
    "lu bac ky",
    "lũ nam kỳ",
    "lu nam ky",
    "lũ trung kỳ",
    "lu trung ky",
    "đồ bắc kỳ",
    "do bac ky",
    "đồ nam kỳ",
    "do nam ky",
    "đồ trung kỳ",
    "do trung ky",
    "dân tỉnh lẻ",
    "dan tinh le",
  ],
  hate_or_threat: [
    "giết",
    "giet",
    "chém",
    "chem",
    "đâm",
    "dam",
    "đâm chết",
    "dam chet",
    "đâm mày",
    "dam may",
    "đốt nhà",
    "dot nha",
    "đập chết",
    "dap chet",
    "xử mày",
    "xu may",
    "cho mày chết",
    "cho may chet",
    "mày liệu hồn",
    "may lieu hon",
    "ra đường coi chừng",
    "ra duong coi chung",
    "tao giết mày",
    "tao giet may",
    "tao chém mày",
    "tao chem may",
    "đánh chết",
    "danh chet",
    "giết cả nhà",
    "giet ca nha",
    "dọa giết",
    "doa giet",
  ],
  grooming: [
  ],
};

module.exports = {
  MODERATION_THRESHOLD,
  AI_MODERATION_CACHE_TTL_MS,
  AI_MODERATION_CACHE_MAX_ENTRIES,
  LINK_PATTERN,
  PHONE_PATTERN,
  EMOJI_ONLY_PATTERN,
  FAST_PATH_SAFE_PHRASES,
  DANGEROUS_KEYWORDS,
};
