const router = require('express').Router(); const { sessionCookieName } = require('../config/env');
router.get('/', (req, res) => res.redirect(req.cookies[sessionCookieName] ? '/dashboard' : '/login'));
router.use(require('./auth.routes'));
router.use(require('./dashboard.routes'));
router.use(require('./user-account.routes'));
router.use(require('./post-management.routes'));
router.use(require('./report-management.routes'));
router.use(require('./notification-campaign.routes'));
router.use(require('./audit-log.routes'));
module.exports = router;
