// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKURrH4gqlL49Jz8b9zarIDk95R0FYQdI',
    appId: '1:758089818242:web:23f10a172074f6d9c5149b',
    messagingSenderId: '758089818242',
    projectId: 'matchu-5bd75',
    authDomain: 'matchu-5bd75.firebaseapp.com',
    storageBucket: 'matchu-5bd75.firebasestorage.app',
    measurementId: 'G-BSMNF0TB65',
    // databaseURL: 'https://matchu-5bd75-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMVtY2c1MO1oO-p67TgdwOpHfZ79X5QAI',
    appId: '1:758089818242:android:adf8aa46b3dc8abdc5149b',
    messagingSenderId: '758089818242',
    projectId: 'matchu-5bd75',
    storageBucket: 'matchu-5bd75.firebasestorage.app',
    // databaseURL: 'https://matchu-5bd75-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodX1GiU2HVhrDmqdExbJqTocDnx850Vg',
    appId: '1:758089818242:ios:02b8d27a11cc001dc5149b',
    messagingSenderId: '758089818242',
    projectId: 'matchu-5bd75',
    storageBucket: 'matchu-5bd75.firebasestorage.app',
    iosBundleId: 'com.example.matchuApp',
    // databaseURL: 'https://matchu-5bd75-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodX1GiU2HVhrDmqdExbJqTocDnx850Vg',
    appId: '1:758089818242:ios:02b8d27a11cc001dc5149b',
    messagingSenderId: '758089818242',
    projectId: 'matchu-5bd75',
    storageBucket: 'matchu-5bd75.firebasestorage.app',
    iosBundleId: 'com.example.matchuApp',
    // databaseURL: 'https://matchu-5bd75-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKURrH4gqlL49Jz8b9zarIDk95R0FYQdI',
    appId: '1:758089818242:web:363cb42da1e13f8bc5149b',
    messagingSenderId: '758089818242',
    projectId: 'matchu-5bd75',
    authDomain: 'matchu-5bd75.firebaseapp.com',
    storageBucket: 'matchu-5bd75.firebasestorage.app',
    measurementId: 'G-BER51CBXPZ',
    // databaseURL: 'https://matchu-5bd75-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
